---

- name: Ensure Supervisor is installed
  apt:
    pkg: supervisor
    state: present
  sudo: yes

# See https://nodesource.com/blog/nodejs-v012-iojs-and-the-nodesource-linux-repositories
- name: Ensure script to install NodeSource Node.js 0.12 repo has been executed
  shell:
    curl -sL https://deb.nodesource.com/setup_0.12 | sudo bash -
    creates=/etc/apt/sources.list.d/nodesource.list
  sudo: yes

- name: Ensure Node.js 0.12 is installed
  apt:
    pkg: nodejs
    state: present
  sudo: yes

- name: Ensure thelounge package is installed
  npm:
    name: thelounge
    global: yes
    production: yes
    version: "1.1.1"
    state: present
  sudo: yes
  notify: Restart supervisord program

- name: Ensure user lounge is present
  user:
    name: lounge
    createhome: no
    comment: The Lounge IRC
    system: yes
    state: present
  sudo: yes

- name: Ensure JS and JSON syntax checking packages are installed
  npm:
    name: "{{ item }}"
    global: yes
    production: yes
    state: present
  with_items:
    - esprima
    - jsonlint
  sudo: yes

- name: Ensure lounge configuration directory is present
  file:
    path: /etc/lounge
    state: directory
  sudo: yes

- name: Ensure The Lounge is configured
  template:
    src: config.js
    dest: /etc/lounge/config.js
    validate: 'esvalidate %s'
  sudo: yes
  notify: Restart supervisord program

- name: Ensure user configuration directory is present
  file:
    path: /etc/lounge/users
    state: directory
  sudo: yes

- name: Ensure user configuration files are present
  template:
    src: user.json.j2
    dest: /etc/lounge/users/{{ item.user }}.json
    owner: lounge
    group: lounge
    mode: "0440"
    force: no # Do not overwrite existing users to not erase networks
    validate: 'jsonlint -q %s'
  with_items: lounge_users
  sudo: yes
  notify: Restart supervisord program

- name: Ensure program configuration for supervisord is installed
  copy:
    src: lounge_supervisord.conf
    dest: /etc/supervisor/conf.d/lounge.conf
  sudo: yes
  notify: Restart supervisord program

- name: Ensure lounge supervisord program is present
  supervisorctl:
    name: lounge
    state: present
  sudo: yes
  notify: Restart supervisord program
